### ISSUE TITLE
Authentication with secret does not work

### ISSUE THREAD

**Issue by rkstro** [lucas-gaitzsch/pdf-turtle#13]
I am using the docker image version 2024.9.23.523-unprivileged, setting the SECRET environment variable with some value so that it works as authentication. After starting the application, I have tried requests to the API without a token or with a different token than the one configured in the environment variable, but the PDF is generated anyway without receiving an error response.

**Comment by lucas-gaitzsch** [comment]
@rkstro Thank you for this bug report. I fixed the issue. 
Could you test it with your configuration? If something still not work, feel you free to repoen the issue or create a new one.
