### ISSUE TITLE
Support headless firefox

### ISSUE THREAD

**Issue by lucas-gaitzsch** [lucas-gaitzsch/pdf-turtle#4]
headless chrome fails to render big html tables as described in here https://github.com/puppeteer/puppeteer/issues/8070

switching to headless firefox fixes the issue as firefox can handle that with ease

_Originally posted by @FluffyDiscord in https://github.com/lucas-gaitzsch/pdf-turtle/issues/2#issuecomment-1382754474_

**Comment by FluffyDiscord** [comment]
Any updates on this please?

**Comment by lucas-gaitzsch** [comment]
This was currently not possible without much effort. The used CDP lib (chromedp) ist not compatible with the CDP like protocol of firefox. I verified it with the chromedp RemoteAllocator.

The adapter for firefox has to be implemented from the scratch.
This is not planned for the next time. If you want to implement the adapter on you own, feel you free to make a pull request.
