### ISSUE TITLE
CSS font url inlining

### ISSUE THREAD

**Issue by lucas-gaitzsch** [lucas-gaitzsch/pdf-turtle#8]
Hi 👋 

I've found this tool incredibly helpful in getting PDF templates up and running with minimal set up, thanks so much.

One small feature request, I'm not able to render the footer with a custom font. I can use this in the body very easily, by including the font file in the assets, and then using the following css inside the header.

```
@font-face {
	font-family: "gill";
	src: url("assets/gill-regular.TTF") format("truetype");
	font-weight: normal;
	font-style: normal;
}

* {
	font-family: "gill", sans-serif;
}
```

Unfortunately, this font is just not found when rendering the footer. I've tried in both the hosted playground (https://pdfturtle.gaitzsch.dev/) and running in a docker container on my local machine.

_Originally posted by @whytekiwi in https://github.com/lucas-gaitzsch/pdf-turtle/issues/2#issuecomment-1667167588_

**Comment by lucas-gaitzsch** [comment]
@whytekiwi 

I have tried to reproduce your issue. I hope the commit ca1b115 will fix this.
Could you test the font rendering with your example?

**Comment by whytekiwi** [comment]
Hi again, and thanks so much for taking the time to investigate this.

I have pulled the latest docker image, and am sad to say that the problem still exists.

I have attached an anonymized bundle file to help with any investigation. Hopefully this helps.

[pdf-turtle-bundle.zip](https://github.com/lucas-gaitzsch/pdf-turtle/files/13505049/pdf-turtle-bundle.zip)

**Comment by lucas-gaitzsch** [comment]
The new change fixes the font inlining (as base64) for your example. 
Unfortunately your example still does not work. This is probably not supported by the Chromium rendering engine. I would recommend that you deliver the desired font directly with the pdf-turtle container (see existing Dockerfile). This eliminates the need to include the font as an asset.
