### ISSUE TITLE
Support for Apple Silicon

### ISSUE THREAD

**Issue by Ditscheridou** [lucas-gaitzsch/pdf-turtle#9]
I tried to start the container today on my M2 Mac and it failed with some weird go errors. I assume that it is not compiled for Apple Silicon, would be nice to have that!

**Comment by lucas-gaitzsch** [comment]
HI,
yes this would be nice. I think you need a docker container for arm64?

**Comment by Ditscheridou** [comment]
yes!

**Comment by lucas-gaitzsch** [comment]
Could you test the latest container build for arm64 with your Apple Device?

**Comment by Ditscheridou** [comment]
Seems to work fine now, awesome!

**Comment by lucas-gaitzsch** [comment]
Thanks for testing!
